apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
spec:
  containers:
    - name: frontend
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 80