apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  labels:
    purpose: define-environment
spec:
  containers:
  - name: env-demo-container
    image: nginx
    env:
    - name: ENVIRONMENT
      value: "production"