apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop
spec:
  selector:
    matchLabels:
      app: roboshop
  template:
    metadata:
      labels:
        app: roboshop
    spec:
      containers:
      - name: roboshop
        image: nginx
        ports:
        - containerPort: 80
